# Generated by Django 3.2.3 on 2021-06-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_emp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='emp_image',
        ),
    ]
