# Generated by Django 3.2.3 on 2021-06-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_emp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='emp_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
