# Generated by Django 3.2.4 on 2021-06-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('trading_outpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('queen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_outpost.queens')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_outpost.my_card')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accept'), ('R', 'Refuse'), ('P', 'Pending')], default='P', max_length=30)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('getter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_outpost.my_card')),
            ],
        ),
    ]
