# Generated by Django 3.2.4 on 2021-06-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_outpost', '0002_my_card_offer_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='card',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='my_card',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='C', max_length=50),
        ),
    ]
