# Generated by Django 3.2.4 on 2021-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_outpost', '0003_auto_20210608_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='name',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='getter',
            new_name='offerer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
        migrations.AlterField(
            model_name='my_card',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('G', 'Give')], default='C', max_length=50),
        ),
    ]
