# Generated by Django 3.2.4 on 2021-06-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_outpost', '0004_auto_20210609_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
