# Generated by Django 3.2.4 on 2021-06-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('forum', '0002_auto_20210607_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
        migrations.AddField(
            model_name='forum',
            name='name',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
