# Generated by Django 3.2.4 on 2021-06-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('forum', '0003_auto_20210607_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.ManyToManyField(null=True, to='accounts.Profile'),
        ),
    ]
