# Generated by Django 3.2.4 on 2021-06-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('forum', '0004_alter_forum_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
        migrations.AddField(
            model_name='forum',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
