# Generated by Django 3.2.4 on 2021-06-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('forum', '0005_auto_20210607_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='discuss',
            new_name='subjet',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='name',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='comment',
        ),
        migrations.AddField(
            model_name='discussion',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('discussion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.discussion')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
