# Generated by Django 3.2.4 on 2021-06-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20210607_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='forum',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
