# Generated by Django 3.2.4 on 2021-06-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20210607_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='subjet',
            new_name='subject',
        ),
    ]
