# Generated by Django 3.2.4 on 2021-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_rename_subjet_discussion_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='topic',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
