# Generated by Django 3.2.4 on 2021-06-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_discussion_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='subject',
            new_name='text',
        ),
    ]
