# Generated by Django 3.2.4 on 2021-06-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='description',
            field=models.CharField(default='TBA', max_length=500),
            preserve_default=False,
        ),
    ]
