# Generated by Django 3.2.4 on 2021-06-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_rooms_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='visitors.rooms'),
        ),
    ]
